//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMarketData.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public long idPedido { get; set; }
        public long idProducto { get; set; }
        public Nullable<long> cantidadProducto { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual ProductoSucursal ProductoSucursal { get; set; }
    }
}
