//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMarketData.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOferta
    {
        public long idProductoEmpresa { get; set; }
        public long idOferta { get; set; }
        public Nullable<int> porcentajeDescuento { get; set; }
        public Nullable<int> CantidadProductosOferta { get; set; }
    
        public virtual oferta oferta { get; set; }
        public virtual ProductoSucursal ProductoSucursal { get; set; }
    }
}
