//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMarketData.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoSolicitudPedido
    {
        public long idSeguimientoSolicitudPedido { get; set; }
        public System.DateTime fechaHoraModificacion { get; set; }
        public Nullable<long> nuevoIdEstado { get; set; }
        public long idSolicitudPedido { get; set; }
    
        public virtual SolicitudPedido SolicitudPedido { get; set; }
        public virtual SolicitudPedidoEstado SolicitudPedidoEstado { get; set; }
    }
}
