//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMarketData.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudPedido()
        {
            this.SeguimientoSolicitudPedido = new HashSet<SeguimientoSolicitudPedido>();
        }
    
        public long idSolicitudPedido { get; set; }
        public Nullable<long> idPedido { get; set; }
        public long idTipoPago { get; set; }
        public long idTipoEnvio { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public int montoPedido { get; set; }
        public long idSolicitudPedidoEstado { get; set; }
        public bool eliminado { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoSolicitudPedido> SeguimientoSolicitudPedido { get; set; }
        public virtual SolicitudPedidoEstado SolicitudPedidoEstado { get; set; }
        public virtual TipodeEnvio TipodeEnvio { get; set; }
        public virtual TipodePago TipodePago { get; set; }
    }
}
